version: "3.3"
services:
  # jaeger:
  #   image: jaegertracing/all-in-one:1.17
  #   restart: always
  #   environment: 
  #     COLLECTOR_ZIPKIN_HTTP_PORT: 9411
  #   ports:
  #   - "5775:5775/udp"
  #   - "6831:6831/udp"
  #   - "6832:6832/udp"
  #   - "5778:5778"
  #   - "16686:16686"
  #   - "14268:14268"
  #   - "14250:14250"
  #   - "9411:9411"
  mongo:
    image: mongo:4.2
    restart: always
    ports:
    - "27017:27017"
    volumes:
      - "${PWD}/compose/database/mongo:/data/db"
  # prom:
  #   image: prom/prometheus
  #   restart: always 
  #   user: '1000'
  #   volumes:
  #     - ${PWD}/compose/database/prom/prometheus.yml:/etc/prometheus/prometheus.yml 
  #     - ${PWD}/compose/database/prom/data/:/prometheus/
  #   ports:
  #     - "9000:9000"
  #   depends_on:
  #     - mongo
  # grafana:
  #   image: grafana/grafana 
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ${PWD}/compose/database/grafana/data:/var/lib/grafana
  #   depends_on:
  #     - prom
  #     - mongo
  
  cvbackend:
    image: brainoom/cvmonitor:v0.3.14
    restart: always
    ports:
      - "8088:8088"
    expose:
      - 8088
    environment:
      CVMONITOR_SAVE_BEFORE_ALIGN: ${CVMONITOR_SAVE_BEFORE_ALIGN:-'FALSE'}
      CVMONITOR_SAVE_AFTER_ALIGN: ${CVMONITOR_SAVE_AFTER_ALIGN:-'FALSE'}
      CVMONITOR_QR_TARGET_SIZE: ${CVMONITOR_QR_TARGET_SIZE:-100}
      CVMONITOR_PORT: 8088
      CVMONITOR_QR_PREFIX: ${CVMONITOR_QR_PREFIX:-""}
    # depends_on: 
    #   - jaeger
  backend:
    image: yehiyam/monitor-backend:v0.0.20
    restart: always
    ports:
      - "80:3000"
    expose:
      - 80
    environment:
      CVMONITOR_HOST: cvbackend
      DB_CONNECTION: mongodb://mongo/test
  #   depends_on:
  #     - cvbackend
  #     - prom
  #     - mongo
  #     - grafana
  #     - jaeger
  frontend:
      image: registry.gitlab.com/or2511/covid-frontend:latest
      restart: always
      ports:
        - "4200:4200"
      expose:
        - 4200
      depends_on: 
        - backend